/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4BOEl7SBoLI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import { Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col h-full">
      <header className="bg-gray-100 dark:bg-gray-800 px-6 py-4 flex items-center justify-between">
        <h1 className="text-lg font-semibold">Debt & Credit History</h1>
        <div className="flex items-center space-x-4">
          <Button size="icon" variant="ghost">
            <CreditCardIcon className="h-5 w-5" />
            <span className="sr-only">Debt</span>
          </Button>
          <Button size="icon" variant="ghost">
            <CreditCardIcon className="h-5 w-5" />
            <span className="sr-only">Credit</span>
          </Button>
        </div>
      </header>
      <div className="flex-1 p-6">
        <Card className="w-full">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Amount</TableHead>
                <TableHead>Type</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">Rent Payment</TableCell>
                <TableCell>$1,200</TableCell>
                <TableCell>
                  <Badge className="bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400" variant="outline">
                    Debt
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Grocery Purchase</TableCell>
                <TableCell>$75</TableCell>
                <TableCell>
                  <Badge className="bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400" variant="outline">
                    Debt
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Paycheck</TableCell>
                <TableCell>$3,500</TableCell>
                <TableCell>
                  <Badge
                    className="bg-green-100 text-green-600 dark:bg-green-900/50 dark:text-green-400"
                    variant="outline"
                  >
                    Credit
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Utility Bill</TableCell>
                <TableCell>$200</TableCell>
                <TableCell>
                  <Badge className="bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400" variant="outline">
                    Debt
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Online Purchase</TableCell>
                <TableCell>$50</TableCell>
                <TableCell>
                  <Badge className="bg-red-100 text-red-600 dark:bg-red-900/50 dark:text-red-400" variant="outline">
                    Debt
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Freelance Work</TableCell>
                <TableCell>$1,000</TableCell>
                <TableCell>
                  <Badge
                    className="bg-green-100 text-green-600 dark:bg-green-900/50 dark:text-green-400"
                    variant="outline"
                  >
                    Credit
                  </Badge>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </Card>
      </div>
    </div>
  )
}

function CreditCardIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>
  )
}
